/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;

/**
 *
 * @author ASUS
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarGUI
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnglassfish = new javax.swing.JButton();
        btnjavaee = new javax.swing.JButton();
        btnpostgresql = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        btnglassfish.setText("GlassFish");
        btnglassfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnglassfishActionPerformed(evt);
            }
        });

        btnjavaee.setText("Java EE");
        btnjavaee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjavaeeActionPerformed(evt);
            }
        });

        btnpostgresql.setText("PostgreSQL");
        btnpostgresql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostgresqlActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnglassfish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnjavaee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpostgresql)
                .addGap(82, 82, 82)
                .addComponent(btnexit)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnglassfish)
                    .addComponent(btnjavaee)
                    .addComponent(btnpostgresql)
                    .addComponent(btnexit))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        imagepanel.setBackground(new java.awt.Color(204, 204, 255));
        imagepanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/glassfish.jpg"))); // NOI18N
        imagepanel.add(jLabel1, "0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/javaee.jpg"))); // NOI18N
        imagepanel.add(jLabel2, "1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/postgresql.jpg"))); // NOI18N
        imagepanel.add(jLabel3, "2");

        getContentPane().add(imagepanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnglassfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnglassfishActionPerformed
    CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "0");
    }//GEN-LAST:event_btnglassfishActionPerformed

    private void btnjavaeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjavaeeActionPerformed
    CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "1");
    }//GEN-LAST:event_btnjavaeeActionPerformed

    private void btnpostgresqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostgresqlActionPerformed
    CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "2");
    }//GEN-LAST:event_btnpostgresqlActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnglassfish;
    private javax.swing.JButton btnjavaee;
    private javax.swing.JButton btnpostgresql;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
